name: Validate Citation

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Manual execution of citation check'

  push:
    branches: [ main ]
    paths:
      - .github/workflows/citation.yml

  pull_request:
    paths:
      - CITATION.cff
      - .github/workflows/citation.yml


jobs:
  Validate-CITATION-cff:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate CITATION.cff
        uses: dieghernan/cff-validator@v3
