name: Validate Citation

on:
  push:
    paths:
      - CITATION.cff
  workflow_dispatch:


jobs:
  Validate-CITATION-cff:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate CITATION.cff
        uses: dieghernan/cff-validator@v3
