name: Unit Tests

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Continuous integration'

  push:
    branches: [ main ]
    paths:
      - .github/workflows/unit-tests.yml

  pull_request:
    branches: [ main ]
    paths:
      - lib
      - modules
      - subworkflows
      - tests
      - nextflow.config
      - main.nf
      - .github/workflows/unit-tests.yml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    continue-on-error: true

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install -r utilities/requirements-dev.txt
          pip install nextflow
          wget -qO- https://get.nf-test.com | bash -s 0.8.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('utilities/docker/unit_tests/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and load Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./utilities/docker/unit_tests/Dockerfile
          load: true
          tags: interproscan6:latest
          cache-from: |
            type=local,src=/tmp/.buildx-cache
            type=gha
          cache-to: |
            type=local,dest=/tmp/.buildx-cache,mode=max
            type=gha,mode=max

      - name: Print environment info
        run: |
          java -version
          nextflow -version
          env

      - name: Run NF-Test unit tests
        shell: bash -l {0}
        run: |
          export PATH=$PATH:$GITHUB_WORKSPACE/nf-test
          ./nf-test test tests/unit_tests
